# Assignment on Numpy

In [2]:
# Create a 1D array of numbers from 0 to 9.

import numpy as np
x = np.arange(10)

print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Create a 3×3 numpy array of all True’s

y = np.full((3,3),True)
print(y)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
# Given an array as input, print only odd numbers as output
arr = [ 1,2,3,4,5,6,7,8,9,11]
odd_arr = []
for i in range(0, len(arr)):
    if arr[i]%2!=0:
        odd_arr.append(arr[i])
print(odd_arr)
        


[1, 3, 5, 7, 9, 11]


In [8]:
# Replace all odd numbers in arr with -2
arr = [ 1,2,3,4,5,6,7,8,9,11]
# odd_arr = []
for i in range(0, len(arr)):
    if arr[i]%2!=0:
        arr[i] = -2
print(arr)


[-2, 2, -2, 4, -2, 6, -2, 8, -2, -2]


In [12]:
# How to reshape an array?

xx = np.array([[2,3,4], [5,6,7]])      
yy = np.reshape(xx, (3, 2))
print("before reshape :\n", xx)

print("after reshape:\n", yy)

before reshape :
 [[2 3 4]
 [5 6 7]]
after reshape:
 [[2 3]
 [4 5]
 [6 7]]


In [15]:
# Convert a 1D array to a 2D array with 2 rows

x = np.arange(10)

array_2 = np.reshape(x,(2,5))
print(array_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
#  Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples.

a = [1,2,3,4,5,6,7,8,9]
b =  []
for i in range(0, len(a)):
    if a[i]%2!=0 or a[i]%4==0:
        b.append(arr[i])
print("b:", b)

b: [1, 3, 4, 5, 7, 8, 9]


In [31]:
# Given array, check if there are any null values and print them out

a = np.array(range(5,20,2))
b = np.append(a, np.nan)
print(b)
c = np.isnan(b)
d =np.argwhere(c)
print(c)
print("index of NaN:", d)

[ 5.  7.  9. 11. 13. 15. 17. 19. nan]
[False False False False False False False False  True]
index of NaN: [[8]]


In [40]:
# How to replace all missing values with 0 in a numpy array?

a = np.array(range(5,20,2))
b = np.append(a, np.nan)
b[np.isnan(b)] = 0
print(b)

# print(np.where(array1=='nan', 0, array1))

[ 5.  7.  9. 11. 13. 15. 17. 19.  0.]


In [47]:
# How to find the count of each unique number in a NumPy array?

arr_1 = [1, 2, 3,3, 4, 5, 6,6, 7, 8, 9,9,9,11,11,11, 11]
aa,bb = np.unique(arr_1, return_counts=True)
print("unique values: ", aa)
print("Count : ", bb)

unique values:  [ 1  2  3  4  5  6  7  8  9 11]
Count :  [1 1 2 1 1 2 1 1 3 4]


In [49]:
#  How to convert a numeric to a categorical (text) array?

import array as arr
a = arr.array('i', [2, 4, 6, 8])
a

array('i', [2, 4, 6, 8])

In [51]:
# Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. 
# Exclude the elements which are divisible by both
a = np.arange(99,300)
b =  []
for i in range(0, len(a)):
    if (a[i]%5==0 or a[i]%7==0) and a[i]%(7*5)!=0:
        b.append(a[i])
print("b:", b)

b: [100, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 145, 147, 150, 154, 155, 160, 161, 165, 168, 170, 180, 182, 185, 189, 190, 195, 196, 200, 203, 205, 215, 217, 220, 224, 225, 230, 231, 235, 238, 240, 250, 252, 255, 259, 260, 265, 266, 270, 273, 275, 285, 287, 290, 294, 295]


In [53]:
# Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

arr = [ 1,2,3,4,5,6,7,8,9,11]

bb = []
for i in range(0, len(arr)):
    bb.append(arr[len(arr)-i-1])
print(bb)

[11, 9, 8, 7, 6, 5, 4, 3, 2, 1]
